import type { NextPage } from "next";
import Head from "next/head";
import Faq from "../components/Faq";
import FeatureGrid from "../components/FeatureGrid";
import Filler from "../components/Filler";
import Footer from "../components/Footer";
import HeroSection from "../components/HeroSection";
import Navbar from "../components/Navbar";
import Services from "../components/Services";
import Stats from "../components/Stats";
import TrialSizeSample from "../components/TrialSizeSample";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroSection />
      <Services />
      <Stats />
      <TrialSizeSample />
      <Faq />
      <Footer />
    </div>
  );
};

export default Home;
